---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject.yaml
  - appset-acs-central.yaml
  - appset-cluster-config.yaml
  - appset-democratic-csi-nfs.yaml
  - appset-egress-ips.yaml
  - appset-hashicorp-vault.yaml
  - appset-hub-dev-services.yaml
  - appset-install-kyverno.yaml
  - appset-kagent-crds.yaml
  - appset-kagent-kmcp.yaml
  - appset-kagent.yaml
  - appset-kubevirt-redfish.yaml
  - appset-mattermost.yaml
  - appset-rocketchat.yaml
  - appset-vlan-stacks.yaml
  - appset-ztp-sync.yaml
  - rhacm-integration.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true