---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject.yaml
  - appset-democratic-csi-nfs.yaml
  - appset-install-kyverno.yaml
  - appset-hashicorp-vault.yaml
  - appset-cluster-config.yaml
  - appset-egress-ips.yaml
  - appset-vlan-stacks.yaml
  - rhacm-integration.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true