---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debug-receiver
  name: debug-receiver
spec:
  ports:
    - name: alert-debug-receiver
      port: 9393
      protocol: TCP
      targetPort: 9393
  selector:
    app: debug-receiver
  sessionAffinity: None
  type: ClusterIP