---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: global-openshift-config
  #namespace: open-cluster-management-policies
spec:
  description: "Global OpenShift configuration policies"
  policies:
    # Policy Generators
    - machine-configuration
    - kubelet-configuration
    - label-nodes

    # Policies
    - root-ca-distribution
    - cluster-info-header
    - configure-idp
    - configure-ingress-certs
    # - configure-idp-login-screen
    - disable-self-provisioner
    - configure-project-template
    - remove-kubeadmin
    - audit-logging-config
    - encrypt-etcd
    - openshift-samples-config
    - image-vuln-scanning
    - enable-multinetworkpolicy
    - compliance-cis-scan
    - compliance-e8-scan