apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - health-checks.yaml
  - global-openshift-config.yaml
  - global-openshift-operators.yaml
  - hub-health-checks.yaml
  - developer-services.yaml
  - operator-bundle-nvidia.yaml
  - operator-bundle-odf.yaml
  - operator-bundle-virt.yaml
  - instance-bundle-virt.yaml
  - instance-bundle-nvidia.yaml
  - instance-bundle-odf-lso-bmh.yaml


commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true