---
controller_credential_types:
- name: PowerDNS Admin Credential
  description: PowerDNS Admin Credential - not the direct API
  inputs:
    fields:
    - type: string
      id: pdns_admin_url
      label: PowerDNS Admin URL
    - secret: true
      type: string
      id: pdns_admin_api_key
      label: PowerDNS Admin API Key
    - type: string
      id: pdns_admin_username
      label: PowerDNS Admin Username
    - type: string
      id: pdns_admin_password
      label: PowerDNS Admin Password
      secret: true
    required:
    - pdns_admin_url
  injectors:
    extra_vars:
      pdns_admin_url: !unsafe "{{ pdns_admin_url }}"
      pdns_admin_username: !unsafe "{{ pdns_admin_username }}"
      pdns_admin_password: !unsafe "{{ pdns_admin_password }}"
      pdns_admin_api_key: !unsafe "{{ pdns_admin_api_key }}"
    env:
      PDNS_ADMIN_URL: !unsafe "{{ pdns_admin_url }}"
      PDNS_ADMIN_USERNAME: !unsafe "{{ pdns_admin_username }}"
      PDNS_ADMIN_PASSWORD: !unsafe "{{ pdns_admin_password }}"
      PDNS_ADMIN_API_KEY: !unsafe "{{ pdns_admin_api_key }}"
