---
controller_credentials:
  - name: RootMachine
    description: SSH Key for connecting to systems via the root user
    credential_type: Machine
    organization: "{{ global_organization }}"
    inputs:
      username: "root"
      ssh_key_data: "{{ lookup('file', ssh_private_key) }}"
      become_method: sudo
      become_username: ""
  - name: AnsibleMachine
    description: SSH Key for connecting to systems via the ansible user
    credential_type: Machine
    organization: "{{ global_organization }}"
    inputs:
      username: "ansible"
      ssh_key_data: "{{ lookup('file', ssh_private_key) }}"
      become_method: sudo
      become_username: ""

  - name: SharedVault
    description: Ansible Vault password to unlock sealed secrets
    credential_type: Vault
    organization: "{{ global_organization }}"
    inputs:
      vault_password: "{{ lookup('file', ansible_vault_password_file) }}"