---
controller_configuration_credentials_secure_logging: false
controller_credentials:
  - name: RootMachine
    description: SSH Key for connecting to systems via the root user
    credential_type: Machine
    organization: "{{ global_organization }}"
    inputs:
      username: "root"
      ssh_key_data: "{{ lookup('file', ssh_private_key) }}"
      become_method: sudo
      become_username: ""
  - name: AnsibleMachine
    description: SSH Key for connecting to systems via the ansible user
    credential_type: Machine
    organization: "{{ global_organization }}"
    inputs:
      username: "ansible"
      ssh_key_data: "{{ lookup('file', ssh_private_key) }}"
      become_method: sudo
      become_username: ""

  - name: SharedVault
    description: Ansible Vault password to unlock sealed secrets
    credential_type: Vault
    organization: "{{ global_organization }}"
    inputs:
      vault_password: "{{ lookup('file', ansible_vault_password_file) }}"

  - name: KemoLabs-PowerDNS
    description: PowerDNS Admin Credential for KemoLabs
    credential_type: PowerDNS Admin Credential
    organization: "{{ global_organization }}"
    inputs:
      pdns_admin_url: "{{ pdns_admin_url }}"
      pdns_admin_api_key: "{{ pdns_admin_api_key }}"
      pdns_admin_username: "{{ pdns_admin_username }}"
      pdns_admin_password: "{{ pdns_admin_password }}"
      pdns_admin_skip_tls_verify: true

  - name: OCP-HubCluster
    description: Local OpenShift Hub Cluster connection
    credential_type: OpenShift or Kubernetes API Bearer Token
    organization: "{{ global_organization }}"
    inputs:
      host: "{{ openshift_api_url }}"
      bearer_token: "{{ openshift_cluster_token }}"
      ssl_ca_cert: "{{ openshift_ca_crt }}"