---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: hub-cicd

resources:
  - namespace.yaml
  - root-ca.yaml
  - rbac.yaml
  - mirror-registries.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true