$ANSIBLE_VAULT;1.1;AES256
31356331373333333537303937396230613831633334646266323237323638343664316138316462
6632316135313637613133633733663663353032343665360a343137386264323337373538643936
38643862373337393335623437656432343665336561373433366339346234656561386331363462
6166343562353637360a376365323961326161616361303165633865663834663931386337363938
66326664623761313134306533393434343737356530616533653131303165363335363533323536
34633637663662663536656233616461646366346339316363306465353238326537623230336631
65346266626136646663343461353537616238653763323432313066623739386333396439633834
66336335656431363035316566333531363436326635636437666362613831353762313333353638
39653831336162383532303039373030393539326233633065343735626532373130343639633165
35363334663563623539346234666339383533643565653735393336356638383039343637616565
36613766353531393032346235396562666431643963383963383939646263333365653862373566
66643833316236626162626666666636626431613936363732323835666465376136646366343936
65666137373631393738643433653866346131663963333862313539383762623034646635316133
31303664363136326432383630613238323062313830323330633138396366613234306263353639
30623734396532393530303435346363626639656464623064303230353439346130343330616537
30373334336333366634
