---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - creds-copy-vault-userpass.yaml
  - loki-format-secret.yaml
  - configure-monitoring.yaml
  - acs-secured-cluster.yaml
  - netobserv-loki-format-secret.yaml
  - rhbk-rhdh-secrets.yaml
  - rhdh-rhdh-secrets.yaml
  - argocd-rhdh-secrets.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true