---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - creds-copy-vault-userpass.yaml
  - loki-format-secret.yaml
  - configure-monitoring.yaml
  - acs-secured-cluster.yaml