---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: hub-cicd

resources:
  - tasks/
  - config/
  - imagestreams/
  - pipelines/

# Namespace Transformer - This will set the namespace to hub-cicd for resources that do not have one specified
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: hub-cicd
    unsetOnly: true

# This doesn't work lol
# configurations:
#   - kConfig-namespace.yml