version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/de-minimal-rhel9:latest'
additional_build_files:
  - src: root-ca/*.pem
    dest: certs

dependencies:
  galaxy:
    collections:
      - ansible.eda
      - name: sabre1041.eda
        version: 1.0.2
      - ansible.eda
      - redhatinsights.eda
      - dynatrace.event_driven_ansible
  python:
    - requests
    - kubernetes
    - asyncio
    - aiokafka
    - aiohttp
    - aiosignal
    - aiomqtt
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - python3.11 [platform:rpm]
    - python3.11-devel [platform:rpm]
    - krb5-devel [platform:rpm]
    - iputils [platform:rpm]
    - gcc [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  append_final:
    - COPY _build/certs/ /etc/pki/ca-trust/source/anchors/
    - RUN update-ca-trust
  # This is a workaround for the bug: https://issues.redhat.com/browse/AAP-32856
    - ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.11/site-packages:/usr/local/lib64/python3.11/site-packages