# Shamelessly stolen from https://github.com/kubealex/eda-decision-environment/blob/main/de-builder.yml
---
version: 3
images:
  base_image:
    name: "quay.io/ansible/ansible-rulebook:latest"
additional_build_files:
  - src: ansible.cfg
    dest: configs
  - src: root-ca/*.pem
    dest: certs

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  append_final:
    - COPY _build/certs/ /etc/pki/ca-trust/source/anchors/
    - RUN update-ca-trust
    - RUN for dir in /home/runner /home/runner/.ansible /home/runner/.ansible/tmp /runner /home/runner /runner/env /runner/inventory /runner/project /runner/artifacts ; do mkdir -m 0775 -p $dir ; chmod -R g+rwx $dir ; chgrp -R root $dir ; done && for file in /home/runner/.ansible/galaxy_token /etc/passwd /etc/group ; do touch $file ; chmod g+rw $file ; chgrp root $file ; done
    - VOLUME /runner
    - WORKDIR /runner
    - ENV HOME=/home/runner