apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - all-openshift-clusters.yaml
  - openshift-4.19-clusters.yaml
  - global.yaml
  - acs-central.yaml
  - acs-secured-cluster.yaml
  - global-hub-cluster.yaml
  - hcp-baremetal.yaml
  - hcp-inception.yaml
  - hcp-kubevirt.yaml
  - hub-cluster.yaml
  - kyverno-policies.yaml

  - bmh-lso-odf.yaml
  - community-eso.yaml
  - developer-services.yaml
  - nvidia-gpu.yaml
  - rh-loki.yaml
  - virtualization.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true