---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - enable-platform-monitoring.yaml
  - disable-platform-monitoring.yaml
  - enable-openshift-console.yaml
  - disable-openshift-console.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true