---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - platform-monitoring/enable-prometheus.yaml
  - platform-monitoring/disable-prometheus.yaml
  - openshift-console/enable.yaml
  - openshift-console/disable.yaml
  - olm-pprof/enable.yaml
  - olm-pprof/disable.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true