generators:
  - policy-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: matrix-red-login-template
    namespace: openshift-config
    files:
      - login.html
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
