---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: hcp-virt-ztp-cluster-two
  namespace: hcp-virt-ztp-cluster-two
spec:
  clusterName: hcp-virt-ztp-cluster-two
  clusterNamespace: hcp-virt-ztp-cluster-two
  clusterLabels:
    cloud: KubeVirt
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
