---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:

  # Operator Installation Policies
  - gitops-base.yaml
  - gitops-1.18.yaml

  - logging-base.yaml
  - logging-6.3.yaml

  - rh-loki-base.yaml
  - rh-loki-6.3.yaml

  - mtc-base.yaml
  - mtc-1.8.yaml

  - aap-base.yaml
  - aap-2.6.yaml


commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true