---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: hcp-kubevirt
  namespace: hcp-kubevirt
spec:
  clusterName: hcp-kubevirt
  clusterNamespace: hcp-kubevirt
  clusterLabels:
    cloud: KubeVirt
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
