---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - acs-secured-cluster.yaml
  - acs-secured-cluster-binding.yaml
  - developer-services-rhbk.yaml
  - loki-format-secret.yaml
  - loki-format-secret-binding.yaml
  - kube-system_community-eso.yaml
  - kube-system_community-eso_binding.yaml
  - netobserv-loki.yaml
  - netobserv-loki-binding.yaml
  - open-cluster-management-observability-all-openshift-clusters.yaml
  - open-cluster-management-observability-all-openshift-clusters-binding.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true