---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki-format-secret.yaml
  - loki-format-secret-binding.yaml
  - kube-system_community-eso.yaml
  - kube-system_community-eso_binding.yaml
  - open-cluster-management-observability-all-openshift-clusters.yaml
  - open-cluster-management-observability-all-openshift-clusters-binding.yaml