---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  # - aap.yaml -- REPLACED BY VERSIONED OPERATOR POLICIES --
  - authorino.yaml
  - cco.yaml
  - cert-manager.yaml
  - compliance.yaml
  - cost-management-metrics.yaml
  - descheduler.yaml
  - dev-hub.yaml
  - devspaces.yaml
  - community-eso.yaml
  - far.yaml
  - gatekeeper.yaml
  - lso.yaml
  - metallb.yaml
  - mtv.yaml
  - network-observability.yaml
  - nfd.yaml
  - nmstate.yaml
  - nmo.yaml
  - nhc.yaml
  - nvidia-gpu.yaml
  - oadp.yaml
  - openshift-builds.yaml
  - odf.yaml
  - pipelines.yaml
  - power-monitoring.yaml
  - rhacs.yaml
  - rhoai.yaml
  - sscsi.yaml
  - snr.yaml
  - talm.yaml
  - virtualization.yaml
  - web-terminal.yaml
  - serverless.yaml
  - servicemesh-3.yaml
  - servicemesh-2.yaml


commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true