---
apiVersion: v1
kind: Secret
metadata:
  name: ztp-git-push-creds
  namespace: ztp-system
type: Opaque
stringData:
  git_url: "https://github.com/kenmoini/lab-ocp.git"
  git_branch: main
  git_user_name: "ZTP Bot"
  git_user_email: "ztp@you.me"
  # git_username: usernameHere # or git if using ssh auth
  # git_password: ""
  # git_ssh_key: |
  #   ------ BEGIN OPENSSH PRIVATE KEY ------
  #   YOUR_SSH_KEY_HERE
  #   ------ END OPENSSH PRIVATE KEY ------