---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nncp-vlan-br-66.yaml
  - nncp-baremetal-network.yml
  - nncp-bond0-vmnet.yaml
  - nad-vm-vlan70.yaml
  - nad-vm-lab-lan.yaml
  - nad-baremetal-network.yaml