---
eda_credentials:
  - name: AAP-Hub
    description: AAP Hub Credentials for being able to start AAP Jobs
    organization: "{{ global_organization | default('Default') }}"
    credential_type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "https://{{ aap_hostname}}"
      password: "{{ aap_password }}"
      username: "{{ aap_username }}"
      verify_ssl: '{{ aap_validate_certs | default(false) }}'